# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("media.navigator.permission.disabled", true);
user_pref("device.storage.enabled", true);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.debugger.chrome-enabled", true);
user_pref("devtools.chrome.enabled", true);
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.tabs.warnOnCloseOtherTabs", false);
user_pref("app.update.auto", false);